services:
  # 1. THE LEADER (Primary Write Node)
  - type: web
    name: pykv-leader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m PyKV.B_server.server
    envVars:
      - key: ROLE
        value: LEADER
      - key: LEADER_PORT
        value: 10000
    disk:
      name: pykv-leader-data
      mountPath: /opt/render/project/src/PyKV/data
      sizeGB: 1

  # 2. THE FIRST REPLICA
  - type: web
    name: pykv-replica-1
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m PyKV.B_server.server
    envVars:
      - key: ROLE
        value: REPLICA
      - key: LEADER_URL
        value: http://pykv-leader:10000
    disk:
      name: pykv-replica-1-data
      mountPath: /opt/render/project/src/PyKV/data
      sizeGB: 1

  # 3. THE SECOND REPLICA (New Service)
  - type: web
    name: pykv-replica-2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m PyKV.B_server.server
    envVars:
      - key: ROLE
        value: REPLICA
      - key: LEADER_URL
        value: http://pykv-leader:10000
    disk:
      name: pykv-replica-2-data
      mountPath: /opt/render/project/src/PyKV/data
      sizeGB: 1

  # 4. THE STREAMLIT DASHBOARD
  - type: web
    name: pykv-ui
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run PyKV/Client/app.py --server.port 10000
    envVars:
      - key: LEADER_URL
        value: https://pykv-leader.onrender.com
      - key: REPLICA_URLS
        value: https://pykv-replica-1.onrender.com,https://pykv-replica-2.onrender.com